"""Pair-manifest schema for human evaluation (Block D.hum)."""
from __future__ import annotations

import json
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Iterable


@dataclass
class Section:
    """A musical section span on a song's timeline."""
    label: str
    start_seconds: float
    end_seconds: float


@dataclass
class Sample:
    """A single song generated by a method, plus its prompt and section spans."""
    method: str
    audio_path: str
    sample_rate: int | None = None
    sections: list[Section] = field(default_factory=list)


@dataclass
class PairManifest:
    """One A/B comparison: same prompt, two methods."""
    pair_id: str
    prompt_id: str
    prompt_text: str
    lyrics: str | None
    sample_a: Sample
    sample_b: Sample
    axes: list[str] = field(default_factory=lambda: [
        "overall", "musicality", "prompt_fit", "lyric_intelligibility", "worst_section_quality",
    ])
    strata: dict = field(default_factory=dict)


def load_manifest(path: str | Path) -> list[PairManifest]:
    path = Path(path)
    out: list[PairManifest] = []
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            raw = json.loads(line)
            raw["sample_a"] = Sample(**{
                **raw["sample_a"],
                "sections": [Section(**s) for s in raw["sample_a"].get("sections", [])],
            })
            raw["sample_b"] = Sample(**{
                **raw["sample_b"],
                "sections": [Section(**s) for s in raw["sample_b"].get("sections", [])],
            })
            out.append(PairManifest(**raw))
    return out


def save_manifest(pairs: Iterable[PairManifest], path: str | Path) -> None:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        for p in pairs:
            f.write(json.dumps(asdict(p), ensure_ascii=False) + "\n")
