"""Prepare dev + held-out prompt sets stratified per METHOD_SPEC §1.3.

⚠️ **DEPRECATED (STOP-B-8 Phase-1, 2026-05-17)**

This script writes TEMPLATE STUBS only (lyrics = "TODO: replace with real lyrics ...").
Production prompts are now generated by:

  scripts/generate_real_prompts.py     — original phrase banks + 60+ short original lyric
                                          fragments + cross-genre fusion + natural-style
                                          rewrites (replaces this scaffold entirely)
  scripts/patch_prompts_quality.py     — in-place quality patch (lyric-overlap repair +
                                          broad → natural-style rewriting)

This file is kept for traceability of the original scaffold approach and as a reference
implementation of the `Prompt` dataclass shape + `MISSING_REAL_PROMPTS.flag` contract.
Do NOT run this script in a tree that already has PI-approved prompts; it would
overwrite them and re-create `MISSING_REAL_PROMPTS.flag`.
"""
from __future__ import annotations

import argparse
import itertools
import random
from pathlib import Path

from mprm.data.prompts import Prompt, save_prompts
from mprm.data.stratification import REQUIRED_STRATA


STRATA_VALUES = {
    "genre": ["pop", "rock", "hip_hop", "classical", "jazz", "electronic", "folk", "metal"],
    "tempo_bin": ["slow_60_90", "med_90_120", "fast_120_160", "very_fast_160_plus"],
    "vocal_vs_instrumental": ["vocal", "instrumental"],
    "lyric_density": ["high", "med", "low", "n_a_instrumental"],
    "structural_complexity": ["simple_AB", "AABA", "verse_chorus", "complex_multi_section"],
    "language": ["en", "zh", "es", "ja", "fr"],
    "prompt_specificity": ["broad", "medium", "specific"],
    "length_bin": ["short_30_60s", "med_60_90s", "long_90_120s"],
}


def stratified_sample(rng: random.Random, n: int) -> list[dict[str, str]]:
    combos = list(itertools.product(*(STRATA_VALUES[k] for k in REQUIRED_STRATA)))
    rng.shuffle(combos)
    selected: list[dict[str, str]] = []
    for combo in combos[:n]:
        selected.append(dict(zip(REQUIRED_STRATA, combo)))
    return selected


def make_prompt(idx: int, prefix: str, strata: dict[str, str], rng: random.Random) -> Prompt:
    text_template = (
        f"A {strata['genre']} song at {strata['tempo_bin']} tempo, "
        f"{strata['vocal_vs_instrumental']} arrangement, "
        f"{strata['structural_complexity']} form, in {strata['language']}."
    )
    lyrics = None
    if strata["vocal_vs_instrumental"] == "vocal":
        lyrics = "TODO: replace with real lyrics matching the strata combination above."
    duration_map = {"short_30_60s": 45.0, "med_60_90s": 75.0, "long_90_120s": 105.0}
    return Prompt(
        prompt_id=f"{prefix}_{idx:04d}",
        text=text_template,
        lyrics=lyrics,
        structure_hint=strata["structural_complexity"],
        duration_target=duration_map[strata["length_bin"]],
        metadata={"todo": "human-review-before-launch"},
        strata=strata,
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--dev-size", type=int, default=256)
    parser.add_argument("--held-out-size", type=int, default=256)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--out-dir", default="configs/prompts")
    args = parser.parse_args()

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    rng = random.Random(args.seed)
    dev = [make_prompt(i, "dev", strata, rng)
           for i, strata in enumerate(stratified_sample(rng, args.dev_size))]
    held_out_rng = random.Random(args.seed + 1)
    held = [make_prompt(i, "held_out", strata, held_out_rng)
            for i, strata in enumerate(stratified_sample(held_out_rng, args.held_out_size))]

    save_prompts(dev, out_dir / "dev.jsonl")
    save_prompts(held, out_dir / "held_out.jsonl")
    flag_path = out_dir / "MISSING_REAL_PROMPTS.flag"
    flag_path.write_text(
        "This file marks the dev and held-out prompt sets as TEMPLATE STUBS.\n"
        "launch_baseline.py will refuse to start while this file exists.\n"
        "Replace the prompt text + lyrics in dev.jsonl and held_out.jsonl with real, stratified\n"
        "prompts (per METHOD_SPEC.md §1.3), then DELETE this flag file to unlock Wave W2.\n"
    )
    print(f"Wrote {len(dev)} dev prompts to {out_dir / 'dev.jsonl'}")
    print(f"Wrote {len(held)} held-out prompts to {out_dir / 'held_out.jsonl'}")
    print(f"Wrote launch flag to {flag_path} — Phase A will REFUSE TO START until this is deleted.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
